-- Add usage tracking columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT 'female';
ALTER TABLE users ADD COLUMN IF NOT EXISTS uploads_left INT DEFAULT 2;
ALTER TABLE users ADD COLUMN IF NOT EXISTS generations_left INT DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS credit_reset_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
