-- Add usage tracking columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS uploads_used INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS generations_used INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS limit_reset_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
