-- Add usage tracking columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS picture_url VARCHAR(255) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS uploads_left INT DEFAULT 2;
ALTER TABLE users ADD COLUMN IF NOT EXISTS generations_left INT DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_payment_at TIMESTAMP DEFAULT NULL;
